---
title: "201to217_demographics"
author: "Carolina Guidolin"
date: "2023-10-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summarise demographic information

Here we summarise demographic information of our sample
```{r}
#Load packages
library(tidyverse)
library(readr)
library(dplyr)
library(gtsummary)
```
Load the data
```{r}
setwd("D:/cyepi/code/descriptive_analysis/demographics")

demog_file <- "201_231_demog_20231123.csv"
demog_data <- read.csv(demog_file, sep = ";")
#Keep demog columns 
demog_data_sel <- demog_data %>%
  select(age, sex, gender, native_language, employment_status) %>%
  mutate(
    sex = recode(sex, "1" ='Female' , "2" = 'Male'),
    gender = recode(gender, "1" = 'Woman', "2" = 'Man'),
    native_language = recode(native_language, "1" = 'English', "0" = 'Other'),
    employment_status = recode(employment_status,
      "0" = 'Full time employed',
      "1" = 'Part time employed',
      "2" = 'Marginally employed (Minijob)',
      "3" = 'Not employed but studying or in training',
      "4" = 'Studying and employed',
      "5" = 'Not employed'
    )
  )
```
```{r}
demog_summary <- demog_data_sel %>%
  tbl_summary(label = list(age ~ "Age", sex ~ "Sex", gender ~ "Gender", native_language~"Native language", employment_status~"Employment status"),
              statistic = list(age ~ "{mean} ({sd})")) 


```


Calulatng summary statistics

```{r pressure, echo=FALSE}
summary_demog <- demog_data_sel%>%
  summarise(mean_age = mean(age),
            sd_age = sd(age),
            female = sum(sex == 1),
            male = sum(sex == 2), 
            woman = sum(gender == 1),
            man = sum(gender == 2), 
            other = sum (gender != 1 & gender != 2))
```

```{r}
##Make a gtsummary table
library(gtsummary)
```

