---
title: "trblshoot_prc"
output: html_document
date: "2024-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
## Varying the other 2 input parameters of the cluster detection function 

## Step 1: vary PIM thresholds
```{r}

#Create a sequence of PIM thresholds at 5 unit steps
pimthresholds <- c(5,10, 15, 20, 25, 30, 35, 40, 45, 50)

#Empty list to store classification results
prc_m_list <- list()

for (threshold in pimthresholds) {
  
  prc_result <- generate_prc(
    dataset = dataset.LL.wrlg,
    low_var = "PIM",
    min_length = 60, #10 minutes (n of observations)
    max_interrupt = 0, #1 minute (n of observations)
    threshold = threshold
  )
  
  # Add the current threshold as a column in prc_m_result
  prc_result <- prc_result %>%
    mutate(threshold = threshold) # Add threshold column
  
  prc_m_list[[threshold]] <- prc_result
  
  
}

prc_pim_1 <- bind_rows(prc_m_list)
#Turn threshold to factor for plotting
# Ensure threshold is numeric with specific levels and labels
prc_pim_1$threshold <- as.numeric(prc_pim_1$threshold)

#Let's plot to see what the result looks like

prc_pim_thresholds <- ggplot() +
   xlim(0,1) + 
   ylim(0,1) +
  geom_abline(slope = 0, intercept = 0.5, linetype = "dashed", color = "darkgrey") + #add a flat line which represents a baseline classifier
  geom_point(data = prc_pim_1, aes(x = TPR, y = PPV, colour = threshold)) +
  scale_colour_gradient(
     name = "PIM threshold",
     low = "blue", high = "lightblue",
     limits= c(5,50),
     guide = guide_colourbar(title.position = "top", title.hjust = 0.5)) +
  labs(x="True positive rate (recall)",
       y = "Positive predictive value \n(precision)",
       title = "Precision-recall curve for detection of \nnon-wear intervals based on activity thresholds",
       subtitle = "Min. length = 10 min, max. interrupt = 0 min") +
   theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        plot.subtitle = element_text(hjust = 0.5, size = 14, color = "grey33"),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.key.size = unit(4, "mm"),
        legend.position = "bottom",
        legend.box = "horizontal") +
   coord_fixed(ratio = 1)

ggsave(filename = "prc_pim_thresholds.png",
       plot = prc_pim_thresholds,
       height = 5.5, 
       width = 6,
       dpi = 600,
       bg = "white",
       path= "D:/cyepi/code/outputs/light_activity_prc/raw/trblshoot_parameters/activity")

```

## Step 2: vary length of interval 
```{r}
#We create min_length ranging from 2 to 11 minutes
min_lengths <- seq(6, 60, by = 6)
#From the previous plot, we know that lower mEDI thresholds are better so we keep it to 1
pim_threshold = 5
#We keep the max_interrupt at 0 minutes
max_interrupt = 0 # 0 minute


#Empty list to store classification results
prc_m_list <- list()

for (min_length in min_lengths) {
  
  prc_result <- generate_prc(
    dataset = dataset.LL.wrlg,
    low_var = "PIM",
    min_length = min_length,
    max_interrupt = max_interrupt,
    threshold = pim_threshold
  )
  
  # Add the current min_length as a column in prc_m_result
  prc_result <- prc_result %>%
    mutate(min_length = min_length) # Add min_length column
  
  prc_m_list[[min_length]] <- prc_result
}

#Turning this into a df 
prc_pim_2 <- bind_rows(prc_m_list)

#Turning min_length into a factor for plotting
prc_pim_2$min_length <- as.factor(prc_pim_2$min_length) 

#Let's plot to see the results
prc_pim_length <- ggplot() +
   xlim(0,1) + 
   ylim(0,1) +
  geom_abline(slope = 0, intercept = 0.5, linetype = "dashed", color = "darkgrey") + #add a flat line which represents a baseline classifier
  geom_point(data = prc_pim_2, aes(x = TPR, y = PPV, colour = min_length)) +
  scale_colour_discrete(
     name = "Min. length (min)",
     labels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)) +
  labs(x="True positive rate (recall)",
       y = "Positive predictive value \n(precision)",
       title = "Precision-recall curve for detection of \nnon-wear intervals based on min. length",
       subtitle = "PIM threshold = 5, max. interrupt = 0 min") +
   theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        plot.subtitle = element_text(hjust = 0.5, size = 14, color = "grey33"),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.key.size = unit(4, "mm"),
        legend.position = "bottom",
        legend.box = "horizontal") +
   coord_fixed(ratio = 1)

ggsave(filename = "prc_pim_length.png",
       plot = prc_pim_length,
       height = 5.5, 
       width = 6,
       dpi = 600,
       bg = "white",
       path= "D:/cyepi/code/outputs/light_activity_prc/raw/trblshoot_parameters/activity")

```

## Step 3: vary max interruption length 
```{r}
#Create a max_interrupt ranging from 0 to 9
max_interrupts <- paste0(seq(0, 54, by = 6))
#From the previous plot, we know that lower mEDI thresholds are better so we keep it to 2
pim_threshold = 5
#We know also know that we shoudl keep the min_length to 10 minutes 
min_length = 60 # 10 minutes


#Empty list to store classification results
prc_m_list <- list()

for (max_interrupt in max_interrupts) {
  
  prc_result <- generate_prc(
    dataset = dataset.LL.wrlg,
    low_var = "PIM",
    min_length = min_length,
    max_interrupt = max_interrupt,
    threshold = pim_threshold
  )
  
  # Add the current max_interrupt as a column in prc_result
  prc_result <- prc_result %>%
    mutate(max_int = max_interrupt) # Add max_interrupt column
  
  prc_m_list[[max_interrupt]] <- prc_result
}

prc_pim_3 <- bind_rows(prc_m_list)

#Turning max_interrupt into a factor for plotting
prc_pim_3$max_int <- as.factor(prc_pim_3$max_int) 

#Let's plot to see the results
prc_pim_interrupt <- ggplot() +
   xlim(0,1) + 
   ylim(0,1) +
  geom_abline(slope = 0, intercept = 0.5, linetype = "dashed", color = "darkgrey") + #add a flat line which represents a baseline classifier
  geom_point(data = prc_pim_3, aes(x = TPR, y = PPV, colour = max_int)) +
  scale_colour_discrete(
     name = "Max. interrupt (min)",
     labels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)) +
  labs(x="True positive rate (recall)",
       y = "Positive predictive value \n(precision)",
       title = "Precision-recall curve for detection of \nnon-wear intervals based on max. interruption",
       subtitle = "PIM threshold = 5, min. length = 10 min") +
   theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        plot.subtitle = element_text(hjust = 0.5, size = 14, color = "grey33"),
        axis.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 8),
        legend.key.size = unit(4, "mm"),
        legend.position = "bottom",
        legend.box = "horizontal") +
   coord_fixed(ratio = 1)

ggsave(filename = "prc_pim_interrupt.png",
       plot = prc_pim_interrupt,
       height = 5.5, 
       width = 6.3,
       dpi = 600,
       bg = "white",
       path= "D:/cyepi/code/outputs/light_activity_prc/raw/trblshoot_parameters/activity")

```


## One plot with all the three curves 
```{r}

library(cowplot)

multiplot <- cowplot::plot_grid(prc_pim_length, prc_pim_thresholds, prc_pim_interrupt,
                                labels = c("A", "B", "C"),
                                ncol = 3,
                                nrow = 1,
                                align = "hv")

ggsave(filename = "pim_prc_parameters_multiplot.png",
       plot = multiplot,
       width = 16.5, 
       height = 5,
       dpi = 600, 
       bg = "white",
       path = "D:/cyepi/code/outputs/light_activity_prc/raw/trblshoot_parameters/activity")

```
